title_h1 = "/html/body/main/div/div[1]/div/div/div/div[1]/div[3]/h1"
brand_h1 = "/html/body/main/div/div[1]/div/div/div/div[1]/div[2]/span"
picture_container = "/html/body/main/div/div[1]/div/div/div/div[2]/div[2]/div[2]/div/div"
price_p = "/html/body/main/div/div[1]/div/div/div/div[1]/div[4]/p"
full_price_p = "/html/body/main/div/div[1]/div/div/div/div[1]/div[4]/p[1]"
promotion_p = "/html/body/main/div/div[1]/div/div/div/div[1]/div[4]/p[2]"
type_with_img_container = "/html/body/main/div/div[1]/div/div/div/div[2]/div[3]/div/div"
product_acessories_title = "/html/body/main/div/div[3]/div/div/div/div/h2"
product_acessories = "/html/body/main/div/div[3]/div/div/div/div/div[1]"
see_more_btn = "/html/body/main/div/div[3]/div/div/div/div/div[2]/button"
product_acessories_more = "/html/body/main/div/div[3]/div/div/div/div/div[3]/div"
main_details_title = "/html/body/main/div/div[2]/div/div/div/div/h2"
main_details = "/html/body/main/div/div[2]/div/div/div/div/p"

special_features = "/html/body/main/div/div[3]/div/div/div/div[2]/div"
